### ISSUE TITLE
how to use telegrambot in code?

### ISSUE THREAD

**Issue by zufan-yp** [mateus-werneck/TelegramBot_MidiaSave#2]
what about other than chat_id and telegram token where are you put?

![image](https://user-images.githubusercontent.com/78656480/116234890-5eedd300-a787-11eb-855f-1dc480ea8692.png)

**Comment by mateus-werneck** [comment]
The Token you can get from the BotMaster on Telegram when creating a bot. As for the chat_id I set as a global variable to print the name and chat_id of someone when they use the bot. If you don't want to print it you can remove from the code =)

**Comment by zufan-yp** [comment]
So what you have to enter in the screenshot above is besides the chat_id, how do you get the url?

**Comment by mateus-werneck** [comment]
> So what you have to enter in the screenshot above is besides the chat_id, how do you get the url?

Chat_id should be null until a user start using the bot, each user have their own unique chat_id. As for the url, it will be the input from the user (instagram, twitter or youtube url). To start using the bot you need to create a TOKEN with BotMaster and assign it where token="TOKEN"

**Comment by zufan-yp** [comment]
i see i know thank you

**Comment by zufan-yp** [comment]
if this is the error where is it usually?

![image](https://user-images.githubusercontent.com/78656480/116250944-65387b00-a798-11eb-8236-15ef0bd65ea9.png)

**Comment by mateus-werneck** [comment]
You need to download geckodriver (Firefox) executable from here https://github.com/mozilla/geckodriver/releases and put on the same folder as telegram_bot.py to use Selenium WebDriver

**Comment by zufan-yp** [comment]
thanksyouu
